### ISSUE TITLE
GeoffR's multi-version "My 10 line spacing values" patch for libnickel

### ISSUE THREAD

**Issue by jackiew1** [pgaskin/kobopatch-patches#25]
@geek1011 
This is what I've been using. I don't know if it answers your question but I think it's working OK. 
I believe the only bits I changed myself are the last 10 lines of ReplaceFloat custom line-height values. You're on your own with the FindBaseAddressHex, ReplaceBytes bits :)

```yaml
My 10 line spacing values - MV:
  - Enabled: no
  - PatchGroup: Line spacing values alternatives
  - Description: |
      This patch changes the values on the line spacing adjustment slider,
      reducing the number of spacing options from 15 to 10, but allowing
      much narrower spacing values to be set.
      Created by GeoffR for fw 4.11.11980 
      https://www.mobileread.com/forums/showpost.php?p=3772937&postcount=248
    # Bypass code-constructed values 1.0, 1.2, 1.5, 2.0, 3.0
  - FindBaseAddressHex: 4F F0 00 09 07 F1 80 01 4F F0 00 08 C3 F6 F0 79 3C 1D F3 58 20 46 61 E9 1E 89 7B 60
  - ReplaceBytes: {Offset: 20, FindH: 20 46 61 E9 1E 89, ReplaceH: 7B 60 03 E0 00 BF}
  - ReplaceBytes: {Offset: 108, FindH: 20 46, ReplaceH: 03 E0}
  - ReplaceBytes: {Offset: 150, FindH: 20 46, ReplaceH: 03 E0}
  - ReplaceBytes: {Offset: 210, FindH: 20 46, ReplaceH: 03 E0}
  - ReplaceBytes: {Offset: 312, FindH: 20 46, ReplaceH: 03 E0}
    # 10 values for replacement, change these replace_float values to suit:
  - FindBaseAddressHex: CD CC CC CC CC CC F0 3F 1F 85 EB 51 B8 1E F1 3F
  - ReplaceFloat: {Offset: 0,  Find: 1.05,  Replace: 0.8}
  - ReplaceFloat: {Offset: 8,  Find: 1.07,  Replace: 0.85}
  - ReplaceFloat: {Offset: 16, Find: 1.1,   Replace: 0.9}
  - ReplaceFloat: {Offset: 24, Find: 1.35,  Replace: 0.92}
  - ReplaceFloat: {Offset: 32, Find: 1.7,   Replace: 0.94}
  - ReplaceFloat: {Offset: 40, Find: 1.8,   Replace: 0.96}
  - ReplaceFloat: {Offset: 48, Find: 2.2,   Replace: 0.98}
  - ReplaceFloat: {Offset: 56, Find: 2.4,   Replace: 1.0}
  - ReplaceFloat: {Offset: 64, Find: 2.6,   Replace: 1.02}
  - ReplaceFloat: {Offset: 72, Find: 2.8,   Replace: 1.04}
```
