### ISSUE TITLE
New beta patch 'KePub stylesheet additions - optimizeLegibility' for fw 4.28.xxxxx

### ISSUE THREAD

**Issue by jackiew1** [pgaskin/kobopatch-patches#93]
```
KePub stylesheet additions - optimizeLegibility:
  - Enabled: no
  - PatchGroup: KePub stylesheet additions alternatives
  - Description: |
        Enables ligatures/kerning in KePubs, but may cause some additional
        rendering problems for fully justified text.
        N.B. May be unsuitable for users who read languages which display vertical text.
  - FindBaseAddressString: ".KBSearchResult, .KBAnnotation, .KBHighlighting {"
  # *** Don't change anything in the 4 ReplaceString lines below ***
  # Create some room to add the extra CSS
  - ReplaceString: {Find: ".KBSearchResult, .KBAnnotation, .KBHighlighting { font-size: 100% !important; -webkit-text-combine: inherit !important; }\n", Replace: ".KBSearchResult,.KBAnnotation,.KBHighlighting{font-size:100%!important;-webkit-text-combine:inherit!important}.KBAnnotatio", MustMatchLength: yes}
  - ReplaceString: {Offset: 122, Find: ".KBAnnotation[writingMode=\"horizontal-tb\"] { border-bottom: 2px solid black !important; }\n", Replace: "n[writingMode=\"horizontal-tb\"]{border-bottom:2px solid #000!important}.KBAnnotation[writin", MustMatchLength: yes}
  - ReplaceString: {Offset: 212, Find: ".KBAnnotation[writingMode=\"vertical-rl\"] { border-right: 2px solid black !important; }\n", Replace: "gMode=\"vertical-rl\"]{border-right:2px solid #000!important}.KBAnnotation[writingMode=\"v", MustMatchLength: yes}
  - ReplaceString: {Offset: 299, Find: ".KBAnnotation[writingMode=\"vertical-lr\"] { border-left: 2px solid black !important; }", Replace: "ertical-lr\"]{border-left:2px solid #000}/*******************************************/", MustMatchLength: yes}
  # *** Don't change anything in the 4 ReplaceString lines above ***
  #
  - FindReplaceString:
        Find:    "/*******************************************/"
        Replace: "body{text-rendering:optimizeLegibility      }"
        MustMatchLength: yes
```
